apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetti-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: olivetti
  template:
    metadata:
      labels:
        app: olivetti
    spec:
      containers:
        - name: olivetti
          image: shubhangi0204/olivetti-face:latest
          ports:
            - containerPort: 5000

